http_access allow all

http_port 3128
https_port 3129 tls-cert=/etc/squid/certs/server.crt tls-key=/etc/squid/certs/server.key

refresh_pattern . 0 0% 0

access_log stdio:/dev/stdout
cache_log stdio:/dev/stderr
